In [1]:
weigth_kg = 60
print(weigth_kg)

60


In [7]:
weigth_kg = 60.3
patient_id = '101'
weigth_lb = weigth_kg * 2.2
patient_id = 'inflam_' + patient_id

print(weigth_lb)
print(patient_id)
print(patient_id, "peso en kilogramos: ", weigth_kg)

132.66
inflam_101
inflam_101 peso en kilogramos:  60.3


In [10]:
print(type(weigth_kg))
print(type(patient_id))

<class 'float'>
<class 'str'>


In [13]:
print('patient_id ' + str(12))

patient_id 12


In [15]:
mass = 47.5
mass = mass * 2.0



print(mass)

95.0


In [16]:
planet = 'Earth'
apples = 5
distance = 10.5

In [27]:
import numpy
data = numpy.loadtxt(fname='python-novice-inflammation-data/data/inflammation-01.csv', delimiter=',')

In [28]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [29]:
print(type(data))

<class 'numpy.ndarray'>


In [30]:
print(data.shape)

(60, 40)


In [33]:
print('El primer elemento de la tabla: ', data[0,0])

El primer elemento de la tabla:  0.0


In [34]:
print('El primer elemento de la tabla: ', data[29,19])

El primer elemento de la tabla:  16.0


In [35]:
#para referirte a la matriz de datos en base a los renglones
#   0 1
#0 [][]
#1 [][]
#2 [][]

In [37]:
#los primeros numeros del data 0:4 muesta solo los 4 renglones y los 0:10 muestra las columnas
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [39]:
print(numpy.mean(data))

6.14875


In [41]:
import time
print(time.ctime)

<built-in function ctime>


In [42]:
maxval, minval, stdval = numpy.amax(data), numpy.amin(data), numpy.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [46]:
patient_0 = data [0, :]
print('maximum inflammation for patient 0: ', numpy.amax(patient_0))

maximum inflammation for patient 0:  18.0


In [49]:
print(numpy.mean(data, axis=1))

[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]


In [51]:
print(numpy.mean(data, axis=0).shape)

(40,)


In [56]:
element = 'oxygen'
print('los primeros 3 caracteres: ', element[0:3])
print('los primeros 3 caracteres: ', element[3:6])


los primeros 3 caracteres:  oxy
los primeros 3 caracteres:  gen


In [73]:
print('los primeros 3 caracteres: ', element[0:-1])

los primeros 3 caracteres:  oxyge


In [76]:
data[16,2]=108
print(data[16,2])

108.0
